title: Piotr PawÅ‚owski # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm creative freelancer working in film and photography industry. I put my first steps in web development around 2005 when playing games with my clan. Yet I was more into design and creation, so i haven't gone into coding. I used to build sites on Wordpress. Now I make a step to become Front-End developer (or even a Full-Stack). I'm recently focused on mastering JavaScript, getting into React/Vue & frameworks (like Animate, AOS, NuxtJs, W3CSS).
  <br><br>
  I currently work mostly with HTML, CSS and basics of JavaScript. I love how todays browser's technologies can deliver dynamic and animated sites.
  <br><br>
  <a href="https://www.ppawlowski.pl/">View My personal site</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
